DatabaseWrapper.schema_editor
Allows migrations in Django 1.7. Error message:

    NotImplementedError: subclasses of BaseDatabaseWrapper may require a
    schema_editor() method